version: '3.8'

services:
  frontend-websockets:
    build:
      context: ../../
      dockerfile: ./apps/frontend-websockets/Dockerfile
    volumes:
      - ./src:/app/apps/frontend-websockets/src
      - ../../libs/shared-ui/src:/app/libs/shared-ui/src
    working_dir: /app/apps/frontend-websockets
    command: "npm run dev"
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - VITE_API_URL=http://localhost:8080